INSERT INTO Categories (name) VALUES ('akcja');
INSERT INTO Categories (name) VALUES ('animacja');
INSERT INTO Categories (name) VALUES ('anime');
INSERT INTO Categories (name) VALUES ('biograficzny');
INSERT INTO Categories (name) VALUES ('dokumentalny');
INSERT INTO Categories (name) VALUES ('dramat');
INSERT INTO Categories (name) VALUES ('familijny');
INSERT INTO Categories (name) VALUES ('fantasy');
INSERT INTO Categories (name) VALUES ('gangsterski');
INSERT INTO Categories (name) VALUES ('historyczny');
INSERT INTO Categories (name) VALUES ('horror');
INSERT INTO Categories (name) VALUES ('kabaret');
INSERT INTO Categories (name) VALUES ('katastroficzny');
INSERT INTO Categories (name) VALUES ('komedia');
INSERT INTO Categories (name) VALUES ('komedia romantyczna');
INSERT INTO Categories (name) VALUES ('koncert');
INSERT INTO Categories (name) VALUES ('kryminał');
INSERT INTO Categories (name) VALUES ('melodramat');
INSERT INTO Categories (name) VALUES ('musical');
INSERT INTO Categories (name) VALUES ('obyczajowy');
INSERT INTO Categories (name) VALUES ('przygodowy');
INSERT INTO Categories (name) VALUES ('przyrodniczy');
INSERT INTO Categories (name) VALUES ('psychologiczny');
INSERT INTO Categories (name) VALUES ('religijny');
INSERT INTO Categories (name) VALUES ('romanse');
INSERT INTO Categories (name) VALUES ('science-fiction');
INSERT INTO Categories (name) VALUES ('sensacyjny');
INSERT INTO Categories (name) VALUES ('serial');
INSERT INTO Categories (name) VALUES ('sportowy');
INSERT INTO Categories (name) VALUES ('szpiegowski');
INSERT INTO Categories (name) VALUES ('thriller');
INSERT INTO Categories (name) VALUES ('western');
INSERT INTO Categories (name) VALUES ('wojenny');

INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Challengers', 29, '2024-04-24', 131, 6.9, 'Tashi, była gwiazda tenisa, zostaje trenerką swojego męża, który aby przerwać pasmo porażek musi zmierzyć się na korcie ze swoim byłym najlepszym przyjacielem, a przy tym byłym partnerem żony.', 'USA', 'Luca Guadagnino');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Civil War', 1, '2024-03-14', 109, 7.4, 'Przez pogrążone w krwawej wojnie domowej Stany Zjednoczone przedziera się grupa dziennikarzy, by w Waszyngtonie przeprowadzić ostatni wywiad z prezydentem.', 'USA', 'Alex Garland');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Diune: Part II', 26, '2024-02-28', 166, 8.4, 'Książę Paul Atryda przyjmuje przydomek MuadDib i rozpoczyna duchowo-fizyczną podróż, by stać się przepowiedzianym w proroctwie wyzwolicielem ludu Diuny.', 'USA', 'Denis Villeneuve');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Nasze magiczne Encanto', 2, '2021-11-24', 99, 7.2, 'Dziewczynka pochodzi z kolumbijskiej rodziny, która obdarzona jest magicznymi mocami. Niestety ona sama nie posiada tego daru.', 'USA', 'Jared Bush');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Piraci z Karaibów: Klątwa Czarnej Perły', 21, '2003-06-28', 143, 7.7, 'Kowal Will Turner sprzymierza się z kapitanem Jackiem Sparrowem, by odzyskać swoją miłość - porwaną córkę gubernatora.', 'USA', 'Gore Verbinski');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Zaplątani', 2, '2010-11-24', 96, 7.6, 'Żyjąca na odludziu Roszpunka, której włosy mają magiczną moc, marzy, by poznać świat. Jej przepustką do wolności jest czarujący łotrzyk Flynn.', 'USA', 'Nathan Greno');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Uncharted', 21, '2022-02-10', 116, 6.1, 'Utalentowany złodziej Nathan Drake zostaje zwerbowany przez doświadczonego poszukiwacza skarbów Victora Sullivana. Razem chcą odnaleźć zaginione złoto Ferdynanda Magellana.', 'USA', 'Ruben Fleischer');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('To', 11, '2017-09-05', 135, 6.7, 'Opowieść o bestii karmiącej się dziecięcym strachem.', 'USA', 'Andy Muschietti');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Tytanic', 13, '1997-11-01', 194, 7.3, 'Rok 1912, brytyjski statek Titanic wyrusza w swój dziewiczy rejs do USA. Na pokładzie emigrant Jack przypadkowo spotyka arystokratkę Rose.', 'USA', 'James Cameron');
INSERT INTO Movies (title, category_id, release_date, duration, rating, description, production_country, director) VALUES ('Shrek', 7, '2001-04-22', 90, 7.8, 'By odzyskać swój dom, brzydki ogr z gadatliwym osłem wyruszają uwolnić piękną księżniczkę.', 'USA', 'Andrew Adamson');

INSERT INTO Actors (firstname, lastname) VALUES ('Zendaya', 'Stoermer Coleman');
INSERT INTO Actors (firstname, lastname) VALUES ('Josh', 'OConnor');
INSERT INTO Actors (firstname, lastname) VALUES ('Mike', 'Faist');
INSERT INTO Actors (firstname, lastname) VALUES ('Kirsten', 'Dunst');
INSERT INTO Actors (firstname, lastname) VALUES ('Cailee', ' Spaeny');
INSERT INTO Actors (firstname, lastname) VALUES ('Wagner', 'Moura');
INSERT INTO Actors (firstname, lastname) VALUES ('Stephen', 'Henderson');
INSERT INTO Actors (firstname, lastname) VALUES ('Nick', 'Offerman');
INSERT INTO Actors (firstname, lastname) VALUES ('Jefferson', 'White');
INSERT INTO Actors (firstname, lastname) VALUES ('Timothee', 'Chalamet');
INSERT INTO Actors (firstname, lastname) VALUES ('Rebecca', 'Ferguson');
INSERT INTO Actors (firstname, lastname) VALUES ('Javier', 'Bardem');
INSERT INTO Actors (firstname, lastname) VALUES ('Josh', 'Brolin');
INSERT INTO Actors (firstname, lastname) VALUES ('Austin', 'Butler');
INSERT INTO Actors (firstname, lastname) VALUES ('Stephanie', 'Beatriz');
INSERT INTO Actors (firstname, lastname) VALUES ('Maria', 'Botero');
INSERT INTO Actors (firstname, lastname) VALUES ('John', 'Leguizamo');
INSERT INTO Actors (firstname, lastname) VALUES ('Mauro', 'Castillo');
INSERT INTO Actors (firstname, lastname) VALUES ('Johnny', 'Depp');
INSERT INTO Actors (firstname, lastname) VALUES ('Geoffrey', 'Rush');
INSERT INTO Actors (firstname, lastname) VALUES ('Orlando', 'Bloom');
INSERT INTO Actors (firstname, lastname) VALUES ('Keira', 'Knightley');
INSERT INTO Actors (firstname, lastname) VALUES ('Mandy', 'Moore');
INSERT INTO Actors (firstname, lastname) VALUES ('Flynn ', 'Rajtar');
INSERT INTO Actors (firstname, lastname) VALUES ('Donna', 'Murphy');
INSERT INTO Actors (firstname, lastname) VALUES ('Ron', 'Perlman');
INSERT INTO Actors (firstname, lastname) VALUES ('Tom', 'Holland');
INSERT INTO Actors (firstname, lastname) VALUES ('Mark', 'Wahlberg');
INSERT INTO Actors (firstname, lastname) VALUES ('Antonio', 'Banderas');
INSERT INTO Actors (firstname, lastname) VALUES ('Sophia', 'Ali');
INSERT INTO Actors (firstname, lastname) VALUES ('Tati', 'Gabrielle');
INSERT INTO Actors (firstname, lastname) VALUES ('Bill', 'Skarsgard');
INSERT INTO Actors (firstname, lastname) VALUES ('Jaeden', 'Martell');
INSERT INTO Actors (firstname, lastname) VALUES ('Jeremy', 'Taylor');
INSERT INTO Actors (firstname, lastname) VALUES ('Sophia', 'Lillis');
INSERT INTO Actors (firstname, lastname) VALUES ('Leonardo', 'DiCaprio');
INSERT INTO Actors (firstname, lastname) VALUES ('Kate', 'Winslet');
INSERT INTO Actors (firstname, lastname) VALUES ('Mike', 'Myers');
INSERT INTO Actors (firstname, lastname) VALUES ('Eddie', 'Murphy');
INSERT INTO Actors (firstname, lastname) VALUES ('Cameron', 'Diaz');
INSERT INTO Actors (firstname, lastname) VALUES ('John', 'Lithgow');

INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (1, 1, 'Tashi');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (1, 2, 'Patrick');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (1, 3, 'Faist');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (2, 4, 'Lee');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (2, 5, 'Jessie');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (2, 6, 'Joel');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (2, 7, 'Sammy');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (2, 8, 'President');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (2, 9, 'Dave');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (3, 10, 'Paul Atryda');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (3, 1, 'Chani');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (3, 11, 'Jessica Atryda');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (3, 12, 'Stilgar');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (3, 13, 'Gurney Halleck');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (3, 14, 'Feyd-Rautha Harkonnen');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (4, 15, 'Mirabel');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (4, 16, 'Grandma Alma');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (4, 17, 'Bruno');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (4, 18, 'Felix');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (5, 19, 'Capitan Jack Sparrow');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (5, 20, 'Capitan Hector Barbossa');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (5, 21, 'Will Turner');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (5, 22, 'Elizabeth Swann');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (6, 23, 'Roszpunka');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (6, 24, 'Flyyn Rajtar');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (6, 25, 'Matka Gertruda');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (6, 26, 'Bracia Karczybokowie');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (7, 27, 'Nathan Drake');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (7, 28, 'Victor Sullivan');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (7, 29, 'Santiago Moncada');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (7, 30, 'Chloe Frazer');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (7, 31, 'Braddock');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (8, 32, 'Pennywise');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (8, 33, 'Bill Denbrough');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (8, 34, 'Ben Hanscom');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (8, 35, 'Beverly Marsh');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (9, 36, 'Jack Dawson');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (9, 37, 'Rose DeWitt Bukater');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (10, 38, 'Shrek / slepa mysz');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (10, 39, 'Osiol');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (10, 40, 'Ksiezniczka Fiona');
INSERT INTO Actors_in_movie (movie_id, actor_id, role) VALUES (10, 41, 'Lord Farquaad');

INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Sulibor', 'Dolata', 'Zamość 77-969 Jutrzenki 327', '515-291-260');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Ewa', 'Słowik', 'Katowice 10-093  Sosnowa 160', '363-979-677');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Ewaryst', 'Dworak', 'Siemianowice Śląskie 81-044 Rzemieniewicka 665', '404-725-511');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Felicja', 'Gruszka', 'Gorzów Wielkopolski 70-948 Freta 841', '743-480-997');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Amira', 'Piskorz', 'Sosnowiec 43-743 Cukiernicza 234', '208-619-313');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Stefania', 'Łukaszewicz', 'Bielsko-Biała Bielsko-Biała Lipowa 432', '287-333-193');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Judyta', 'Doliński', 'Wrocław 02-295 Akacjowa 291', '415-425-630');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Bernadeta', 'Kulesza', 'Gorzów Wielkopolski 45-608 Żytnia 231', '604-813-038');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Józefina', 'Perkowski', 'Sopot 25-345 Słowackiego 69', '583-420-921');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Miłosława', 'Kiełbasa', 'Tarnobrzeg 51-634 Leśna 81a', '563-508-811');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Eugeniusz', 'Stępniewski', 'Świnoujście 29-318 Przedmieście 621b', '365-347-928');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Baltazar', 'Andrzejczak', ' Olsztyn 04-519 Kilińskiego 98', '608-948-284');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Jaromira', 'Kawecki', 'Wrocław 17-701 Klasztorna 135a', '940-871-026');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Paula', 'Nowakowski', ' Tarnobrzeg 39-600 Leśna 709', '203-382-722');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Ida', 'Flis', 'Przemyśl 15-399 Herbaciana 55c', '236-462-162');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Antoni', 'Sidor', 'Białystok 76-676 Kujawska 36a', '331-305-493');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Helga', 'Chmiel', 'Słupsk 87-559 Żytnia 70', '215-103-396');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Bojana', 'Chmielewski', 'Łomża 94-962 Szkolna 774', '238-976-688');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Edyta', 'Dziuba', ' Leszno 29-480 Hebanowa 14', '538-933-400');
INSERT INTO Clients (firstname, lastname, address, phone) VALUES ('Jasława', 'Ziółkowski', 'Elbląg 79-419 Moniuszki 43', '676-858-116');

INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('1', '1', 'Y');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('2', '8', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('3', '10', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('4', '5', 'Y');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('5', '3', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('6', '2', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('7', '3', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('8', '9', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('9', '5', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('10', '8', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('11', '1', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('12', '3', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('13', '6', 'Y');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('14', '5', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('15', '8', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('16', '1', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('17', '9', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('18', '4', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('19', '1', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('20', '5', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('21', '10', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('22', '9', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('23', '1', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('24', '1', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('25', '10', 'Y');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('26', '8', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('27', '10', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('28', '6', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('29', '3', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('30', '1', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('31', '5', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('32', '8', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('33', '10', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('34', '5', 'Y');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('35', '10', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('36', '4', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('37', '1', 'Y');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('38', '8', 'N');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('39', '4', 'Y');
INSERT INTO Copy (copy_id, movie_id, on_loan) VALUES ('40', '6', 'N');

/* UZUPEŁNIĆ TABELE RENTAL */

/* UZUPEŁNIĆ TABELE RESERVATION */
